package day8

import "testing"

func TestSolvePart1a(t *testing.T) {
	input := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`
	expected := 14

	result := SolvePart1(input)

	if result != expected {
		t.Errorf("expected %d actual %d", expected, result)
	}
}

func TestSolvePart1b(t *testing.T) {
	input := `..........
..........
..........
....a.....
........a.
.....a....
..........
......A...
..........
..........`
	expected := 3

	result := SolvePart1(input)

	if result != expected {
		t.Errorf("expected %d actual %d", expected, result)
	}
}

func TestSolvePart1c(t *testing.T) {
	input := `..........
..........
..........
....a.....
........a.
.....a....
..........
..........
..........
..........`
	expected := 4

	result := SolvePart1(input)

	if result != expected {
		t.Errorf("expected %d actual %d", expected, result)
	}
}

func TestSolvePart1d(t *testing.T) {
	input := `..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
..........`
	expected := 2

	result := SolvePart1(input)

	if result != expected {
		t.Errorf("expected %d actual %d", expected, result)
	}
}

func TestSolvePart2(t *testing.T) {
	input := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`
	expected := 34

	result := SolvePart2(input)

	if result != expected {
		t.Errorf("expected %d actual %d", expected, result)
	}
}
